library(tm)
library(NLP)
library(ggplot2)
library(RColorBrewer)
library(wordcloud)
library(cluster)
library(fpc)
library(igraph)
library(httr)
library(MASS)
library(grid)
library(colorspace)
library(lattice)
library(biclust)
library(SnowballC)
getwd()
mytext <- readLines("article.txt")
str(readLines("article.txt"))
text_colla <- paste(readLines("article.txt"), collapse = " ")
text_clean <- gsub(pattern = "\\W", replace=" ", text_colla)
text_clean <- gsub(pattern = "\\d", replace=" ", text_clean)
text_clean <- tolower(text_clean)
text_clean <- removeWords(text_clean, stopwords())
text_clean <- removeWords(text_clean, c("global", "nielsen","also","north","can","weeks","said","one"))
#text_clean <- removeWords(text_clean, c("company", "shall","meeting","security","may","holders","holder"))
#text_clean <- removeWords(text_clean, c("securities","new","person","director","directors","zealand"))
text_clean <- gsub(pattern = "\\b[A-z]\\b{1}", replace=" ", text_clean)
text_clean <- gsub(pattern = "\\bo\\b{2}", replace=" ", text_clean)
text_clean <- stripWhitespace(text_clean)
text_corpus <- Corpus(VectorSource(text_clean))
text_corpus2 <- TermDocumentMatrix(text_corpus) 
m <- as.matrix(text_corpus2)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 10)
set.seed(123)
wordcloud(words = d$word, freq = d$freq, min.freq = 5,
          max.words=700, random.order=F, rot.per=0.45, 
          colors=brewer.pal(9, "Paired"))

#---------------------
tdm <- TermDocumentMatrix(text_corpus)
m <- as.matrix(tdm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
pal <- brewer.pal(12, "BuGn")
pal <- pal[-(1:2)]
png("wordcloud.png", width=1280,height=800)
wordcloud(d$word,d$freq, scale=c(8,.3),min.freq=5,max.words=300, random.order=T, rot.per=.15, colors=pal, vfont=c("sans serif","plain"))
dev.off()
#---------------------

text_clean <- removeWords(text_clean, c("will", "stores","store","per","now","minutes","fuel","brand","read","new"))
text_clean <- gsub(pattern = "\\b[A-z]\\b{1}", replace=" ", text_clean)
text_clean <- gsub(pattern = "\\bo\\b{2}", replace=" ", text_clean)
text_clean <- stripWhitespace(text_clean)
text_corpus <- Corpus(VectorSource(text_clean))
tdm <- TermDocumentMatrix(text_corpus, control = list(wordLengths = c(1, Inf)))
(freq.terms <- findFreqTerms(tdm, lowfreq = 5))
inspect(dtm[1:2,1:5,])
inspect(tdm)
#DocumentTermMatrix (documents: 2, terms: 5)
# inspect frequent words occur more or equal often than lowfreq times
term.freq <- rowSums(as.matrix(tdm))
term.freq <- subset(term.freq, term.freq >= 10)
df <- data.frame(term = names(term.freq), freq = term.freq) 
ggplot(df, aes(x=term, y=freq)) + geom_bar(stat="identity") + xlab("Terms") + ylab("Count") + coord_flip() + theme(axis.text=element_text(size=7))

